name: mindease
description: MindEase â€” A simple mental wellness Flutter application.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  audioplayers: ^4.0.1
  path: ^1.9.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
