name: mindease
description: MindEase â€” A simple mental wellness Flutter application.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  audioplayers: ^4.0.1
  path: ^1.9.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio1.mp3
    - assets/audio2.mp3
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
    - assets/image7.jpg
    - assets/image8.jpg
    - assets/image9.jpg
    - assets/image10.jpg
    - assets/image11.jpg
    - assets/image12.jpg
    - assets/image13.jpg
